# Écoute IPv4
listen=YES
listen_ipv6=NO

# Accès utilisateurs
anonymous_enable=NO
local_enable=YES
write_enable=YES

# Journalisation
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log

# Isolation des utilisateurs locaux
chroot_local_user=YES
local_root=/home/ftpuser/ftp

# Authentification
pam_service_name=vsftpd

# TLS désactivé dans cet exemple de lab
ssl_enable=NO
